---
dist: trusty
sudo: required
rvm:
  - 2.2

env:
  - distribution: centos
    version: 6
  - distribution: centos
    version: 7
  - distribution: ubuntu
    version: 16.04
  - distribution: ubuntu
    version: 14.04
  - distribution: ubuntu
    version: 12.04
  - distribution: alpine
    version: 3.4

before_install:
## No Xenial, https://github.com/travis-ci/travis-ci/issues/5821
#  - sudo apt install lxd
  - sudo apt -t trusty-backports install lxd
  # Pull container
#  - lxc remote add images images.linuxcontainers.org
  - lxc remote list
  - lxc image list
  - 'lxc image copy images:/${distribution}/${version}/amd64 local: --alias=${distribution}-${version}'
  - gem install kitchen
  - gem install kitchen-lxd
  - env
  - pwd
  - find -ls
  - cat /etc/default/lxd-bridge

script:
#  - KITCHEN_LOCAL_YAML=.kitchen.local.yml bundle exec kitchen verify ${INSTANCE}
  - kitchen verify ${INSTANCE} -l debug

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

