# Appveyor artifacts to github release
# more a demonstrator on a simple role that really useful
# ... no virtualbox. just docker. lxd?
# https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux
image: ubuntu
version: '0.8.{build}'

environment:
  PACKER_LOG_PATH: "packerlog.txt"
  PACKER_LOG: 1

before_build:
- uname -a
- lsb_release -a
- env
- pwd
- find -ls
- sudo apt-get update -qq
- sudo apt -y install lxd acl python-pip -qq
- lxc remote list
- "lxc image copy ubuntu-daily:bionic local:"
- lxc image list
- packer -v
- sudo -H pip install ansible
- ansible --version
- lxd --version
- ansible-doc -t connection lxd
- cd ..; ln -s ansible-adduser juju4.adduser; cd juju4.adduser

build_script:
- cd packer && packer build -only=lxd packer-adduser-lxd-bionic.json

after_build:
- ls packer/build

on_failure:
- cat packerlog.txt

artifacts:
- path: packer/build/*

# https://www.appveyor.com/docs/deployment/github/
deploy:
  release: adduser-lxd-image-v$(appveyor_build_version)
  description: 'Appveyor automated lxd image release'
  provider: GitHub
  auth_token:
    secure: <your encrypted token>
  artifact: /build\.*/
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
