---

- name: Add deploy user
  user: name={{ common_deploy_user_name }} password="{{ COMMON_DEPLOY_PASSWORD }}" comment="{{ common_deploy_user_comments }}" shell=/bin/bash
  when: ansible_distribution != 'OpenBSD'

- name: Add deploy user
  user: name={{ common_deploy_user_name }} shell=/bin/ksh
  when: ansible_distribution == 'OpenBSD'

- name: Add authorized keys for {{ common_deploy_user_name }} user
  authorized_key: 
    "user='{{ common_deploy_user_name }}' key='{{ item }}'"
  with_file: common_deploy_public_keys
  when: common_deploy_public_keys is defined and adduser_sshkey_options is not defined
- name: Add authorized keys for {{ common_deploy_user_name }} user - key_options
  authorized_key: 
    user: "{{ common_deploy_user_name }}"
    key: "{{ item }}"
    key_options: "{{ adduser_sshkey_options }}"
  with_file: common_deploy_public_keys
  when: common_deploy_public_keys is defined and adduser_sshkey_options is defined


- name: SSH authorized_keys {{ common_deploy_user_name }}
  file:
    dest=/home/{{ common_deploy_user_name }}/.ssh owner={{ common_deploy_user_name }} mode=700 state=directory

- name: Add deploy user to sudoers
  lineinfile: "dest=/etc/sudoers regexp='^{{ common_deploy_user_name }} ALL' line='{{ common_deploy_user_name }} ALL=(ALL) NOPASSWD: ALL' state=present"
  when: common_deploy_sudoroot is defined and common_deploy_sudoroot
